"""One-command benchmark report: a cross-dataset generalization HTML report from
any folder of NILM-Parquet datasets. Powers `nilmlite bench`.
"""
from __future__ import annotations

from pathlib import Path

from .baselines import Linear, Mean
from .io import Dataset, load_building
from .matrix import cross_dataset_matrix, matrix_html

__all__ = ["discover_specs", "benchmark_report"]


def discover_specs(data_dir: str | Path):
    """Find NILM-Parquet datasets under `data_dir` (each has manifest.json).

    For each, train on all-but-last building, test on the last (cross-building);
    a single-building dataset trains and tests on itself.
    """
    specs = []
    for d in sorted(Path(data_dir).iterdir() if Path(data_dir).is_dir() else []):
        if not (d / "manifest.json").is_file():
            continue
        try:
            ds = Dataset(d)
        except Exception:
            continue
        b = [bb for bb in sorted(ds.buildings) if (d / f"building{bb}.parquet").is_file()]
        if not b:
            continue
        train, test = (b[:-1], b[-1]) if len(b) > 1 else (b, b[0])
        specs.append({"name": ds.manifest.name or d.name, "path": str(d),
                      "train": train, "test": test})
    return specs


def _has(spec, app):
    cols = set(load_building(Path(spec["path"]) / f"building{spec['test']}.parquet").columns)
    return app in cols


def benchmark_report(specs, appliance, out, deep=False, period_s=60, window=99):
    specs = [s for s in specs if _has(s, appliance)]
    if len(specs) < 2:
        raise SystemExit(f"need >=2 datasets containing '{appliance}'; found {len(specs)}")
    models = [("Mean", Mean), ("Linear", lambda: Linear(l2=5.0))]
    if deep:
        from .models_torch import ZOO
        models.append(("Seq2Point", lambda: ZOO["Seq2Point"](window=window, epochs=6)))

    mats = []
    for name, mk in models:
        print(f"  matrix · {name} …")
        res = cross_dataset_matrix(specs, appliance, mk, period_s=period_s, window=window)
        res["model"] = name
        mats.append(res)

    names = [s["name"] for s in specs]
    body = "".join(f"<h3>{m['model']}</h3>{matrix_html(m)}" for m in mats)
    html = f"""<!doctype html><meta charset="utf-8"><title>nilmlite · {appliance} benchmark</title>
<style>
 body{{background:#0c1018;color:#eef2f8;font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:840px;margin:40px auto;padding:0 18px;line-height:1.5}}
 h1{{font-family:Georgia,serif}} h1 .a{{color:#e4634f}} h3{{margin:22px 0 6px}}
 .sub{{color:#8b93a4}} a{{color:#e4634f}}
 table.mtx{{border-collapse:collapse;width:100%;font-variant-numeric:tabular-nums;margin-bottom:8px}}
 .mtx th,.mtx td{{padding:9px;border-bottom:2px solid #0c1018}} .mtx th{{color:#8b93a4;font-size:12px;text-transform:uppercase}}
 .note{{background:#141a26;border:1px solid #222c3d;border-left:3px solid #e4634f;border-radius:10px;padding:12px 16px;margin:18px 0}}
</style>
<h1>nilm<span class="a">lite</span> · {appliance} generalization</h1>
<p class="sub">MAE in watts · train ↓ / test → · lower (greener) is better · datasets: {', '.join(names)}</p>
<div class="note">The <b>diagonal</b> is within-dataset; the <b>off-diagonal</b> is cross-dataset.
A model that only learns the training distribution lights up red off-diagonal — that's the deployment gap.</div>
{body}
<p class="sub" style="margin-top:24px">generated by <code>nilmlite bench</code> · <a href="https://github.com/sustainability-lab/nilmlite">github.com/sustainability-lab/nilmlite</a></p>"""
    out = Path(out)
    out.write_text(html)
    return out
